package rebote_pelotas;

import javax.swing.JLabel;

public class frame_pelotas extends javax.swing.JFrame {

    /**
     * Creates new form FrPelotas
     */
    public frame_pelotas() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.btn_verde.setEnabled(false);
        this.btn_amar.setEnabled(false);
        this.btn_nar.setEnabled(false);
        this.btn_rojo.setEnabled(false);
        this.btn_detener.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        lbl_p1 = new javax.swing.JLabel();
        lbl_p2 = new javax.swing.JLabel();
        lbl_p3 = new javax.swing.JLabel();
        lbl_p4 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        btn_iniciar = new javax.swing.JButton();
        btn_verde = new javax.swing.JButton();
        btn_nar = new javax.swing.JButton();
        btn_rojo = new javax.swing.JButton();
        btn_amar = new javax.swing.JButton();
        btn_detener = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rebote_pelotas/rojo.png"))); // NOI18N

        lbl_p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rebote_pelotas/verde.png"))); // NOI18N

        lbl_p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rebote_pelotas/naranja.png"))); // NOI18N

        lbl_p4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rebote_pelotas/amarillo.png"))); // NOI18N

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lbl_p1)
                .addGap(56, 56, 56)
                .addComponent(lbl_p2)
                .addGap(79, 79, 79)
                .addComponent(lbl_p3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(lbl_p4)
                .addGap(51, 51, 51))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_p4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_p3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(254, 254, 254))
        );

        Titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Titulo.setText("REBOTE - PELOTAS");

        btn_iniciar.setText("Iniciar");
        btn_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarActionPerformed(evt);
            }
        });

        btn_verde.setText("Verde");
        btn_verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verdeActionPerformed(evt);
            }
        });

        btn_nar.setText("Naranja");
        btn_nar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_narActionPerformed(evt);
            }
        });

        btn_rojo.setText("Rojo");
        btn_rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rojoActionPerformed(evt);
            }
        });

        btn_amar.setText("Amarillo");
        btn_amar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_amarActionPerformed(evt);
            }
        });

        btn_detener.setText("Detener");
        btn_detener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detenerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(Titulo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_amar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_nar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_verde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_rojo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_detener, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Titulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_rojo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_verde)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_nar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_amar))
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_iniciar)
                    .addComponent(btn_detener))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getlbl_p1() {
        return lbl_p1;
    }

    hilo_pelotas h_p1, h_p2, h_p3, h_p4;
    boolean p1 = false, p2 = false, p3 = false, p4 = false;


    private void btn_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarActionPerformed

        this.btn_verde.setEnabled(true);
        this.btn_amar.setEnabled(true);
        this.btn_nar.setEnabled(true);
        this.btn_rojo.setEnabled(true);
        this.btn_detener.setEnabled(true);

        lbl_p1.setLocation(20, 0);
        lbl_p2.setLocation(140, 0);
        lbl_p3.setLocation(240, 0);
        lbl_p4.setLocation(350, 0);

        h_p1 = new hilo_pelotas(lbl_p1, this);
        h_p2 = new hilo_pelotas(lbl_p2, this);
        h_p3 = new hilo_pelotas(lbl_p3, this);
        h_p4 = new hilo_pelotas(lbl_p4, this);

        h_p1.start();
        h_p2.start();
        h_p3.start();
        h_p4.start();

        this.p1 = true;
        this.p2 = true;
        this.p3 = true;
        this.p4 = true;

        this.btn_iniciar.setEnabled(false);
    }//GEN-LAST:event_btn_iniciarActionPerformed


    private void btn_verdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verdeActionPerformed
        if (comprueba_pelota(2)) {
            h_p2.stop();
            this.p2 = false;
        } else {
            h_p2 = new hilo_pelotas(lbl_p2, this);
            h_p2.start();
            this.p2 = true;

        }
    }//GEN-LAST:event_btn_verdeActionPerformed

    private void btn_narActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_narActionPerformed
        if (comprueba_pelota(3)) {
            h_p3.stop();
            this.p3 = false;
        } else {
            h_p3 = new hilo_pelotas(lbl_p3, this);
            h_p3.start();
            this.p3 = true;

        }
    }//GEN-LAST:event_btn_narActionPerformed

    private void btn_rojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rojoActionPerformed
        if (comprueba_pelota(1)) {
            h_p1.stop();
            this.p1 = false;
        } else {
            h_p1 = new hilo_pelotas(lbl_p1, this);
            h_p1.start();
            this.p1 = true;

        }
    }//GEN-LAST:event_btn_rojoActionPerformed

    private void btn_amarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_amarActionPerformed
        if (comprueba_pelota(4)) {
            h_p4.stop();
            this.p4 = false;
        } else {
            h_p4 = new hilo_pelotas(lbl_p4, this);
            h_p4.start();
            this.p4 = true;

        }
    }//GEN-LAST:event_btn_amarActionPerformed

    private void btn_detenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detenerActionPerformed
        this.btn_iniciar.setEnabled(true);
        this.btn_verde.setEnabled(false);
        this.btn_amar.setEnabled(false);
        this.btn_nar.setEnabled(false);
        this.btn_rojo.setEnabled(false);

        h_p1.stop();
        this.p1 = false;
        h_p2.stop();
        this.p3 = false;
        h_p3.stop();
        this.p3 = false;
        h_p4.stop();
        this.p4 = false;
        
        this.btn_detener.setEnabled(false);
        this.btn_iniciar.setText("Reiniciar");

    }//GEN-LAST:event_btn_detenerActionPerformed

    private boolean comprueba_pelota(int p) {

        boolean corre_pelota = false;

        switch (p) {
            case 1:
                corre_pelota = p1;
                break;
            case 2:
                corre_pelota = p2;
                break;
            case 3:
                corre_pelota = p3;
                break;
            case 4:
                corre_pelota = p4;
                break;

        }

        return corre_pelota;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame_pelotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame_pelotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame_pelotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame_pelotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame_pelotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btn_amar;
    private javax.swing.JButton btn_detener;
    private javax.swing.JButton btn_iniciar;
    private javax.swing.JButton btn_nar;
    private javax.swing.JButton btn_rojo;
    private javax.swing.JButton btn_verde;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_p1;
    private javax.swing.JLabel lbl_p2;
    private javax.swing.JLabel lbl_p3;
    private javax.swing.JLabel lbl_p4;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
